java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    deps = [],
    visibility = [
        "//src/test/java/me/psanders/utils:__pkg__",
        "//src/main/java/me/psanders/graph/path:__pkg__"
    ]
)
