java_library(
    name = "graph",
    srcs = glob(["*.java"]),
    deps = [
        "@google_maps_services//jar"
    ],
    visibility = [
        "//:__pkg__",
        "//src/main/java/me/psanders/graph/pathfinder:__pkg__"
    ]
)
