java_library(
    name = "graph",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/main/java/me/psanders:__pkg__",
        "//src/main/java/me/psanders/graph/path:__pkg__",
        "//src/test/java/me/psanders/graph/path:__pkg__",
    ]
)
