java_library(
    name = "path",
    srcs = glob(["*.java"]),
    deps = [
        "//src/main/java/me/psanders/graph:graph",
        "//src/main/java/me/psanders/utils:utils"
    ],
    visibility = [
        "//:__pkg__",
        "//src/test/java/me/psanders/graph/path:__pkg__"
    ]
)
